base_url = "https://localhost:1111"
compile_sass = true
build_search_index = true
generate_feed = true
minify_html = true

title = "My blog"
description = "A dummy blog"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
socials = [
	{ name = "Github", url = "https://github.com" },
	{ name = "Gitlab", url = "https://gitlab.com" },
]
license = { name = "CC-BY-SA-4.0", url = "https://creativecommons.org/licenses/by-sa/4.0/" }
